service: whabot-ai-companion-function

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-south-1

functions:
  whabot-ai-companion:
    handler: src/app.handler
    events:
      - http: 
          path: /webhook
          method: POST
          cors: true
      - http: 
          path: /webhook
          method: GET
          cors: true
    layers: 
      - arn:aws:lambda:ap-south-1:776723440099:layer:NodejsDependenciesLayer:2

package:
  individually: true
  excludeDevDependencies: true
  include: 
    - ../src/**
  exclude:
    - ../nodejs_layer
