service: whabot-ai-companion-layer

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-south-1
    
layers:
  NodejsDependenciesLayer:
    path: ../nodejs_layer/node_modules # Path to your layer content
    compatibleRuntimes:
      - nodejs18.x

package:
  individually: true
  include: 
    - ../nodejs_layer/**

custom:
  scriptHooks:
    after:deploy:finalize:
      - serverless deploy --config serverless_lambda.yml
