service: whabot-ai-companion-layer

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-south-1
    
layers:
  NodejsDependenciesLayer:
    path: ../nodejs_layer # Path to your layer content
    compatibleRuntimes:
      - nodejs18.x

package:
  individually: true
  include: 
    - ../nodejs_layer/**
